image:
  repository: us-central1-docker.pkg.dev/trenton-production-c5cb9af5/trenton/trenton-core
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: gcr-pull-secret

service:
  port: 5000

config:
  TRENTON_LOGGING_LOG_TARGET: Json
