#!/usr/bin/env bash

set -eo pipefail
SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
# shellcheck source=../.common
. "${SCRIPT_PATH}"/../.common
# shellcheck source=.common
. "${SCRIPT_PATH}"/.common

cd "${SCRIPT_PATH}/../../core"

detach=""
gcp_vol=""
while getopts "dg:" options; do
  case ${options} in
    d) detach="--detach" ; shift $((OPTIND-1)) ;;
    g)
      cat $OPTARG | wc -c
      gcp_vol="-v ${OPTARG}:/etc/secrets/google/credentials.json:ro"; shift $((OPTIND-1)) ;;
    *) error "Unknown option: -${OPTARG}"; exit 1 ;;
  esac
done

set -x
docker run \
  --name server \
  -p 5000:5000 \
  --network "${DOCKER_COMPOSE_NETWORK}" \
  --env-file .env \
  ${detach} \
  ${gcp_vol} \
  "${COMMON_DOCKER_IMAGE_BASE}/${IMAGE_NAME}:${COMMON_COMMIT_SHA}"
