#!/usr/bin/env bash

set -euo pipefail

script_path="$(
  cd "$(dirname "$0")"
  pwd -P
)"
# shellcheck source=../.common
. "${script_path}/../.common"

cd "${script_path}"/../../helm_vars

helm_cmd="helm"

chart=${1?A Helm chart must be specified}
version=${2?A commit hash must be specified}
environment=${3?An environment must be specified}
namespace=${4?A Kubernetes namespace must be specified}

env_vars="${chart}/${environment}"
[[ -d "${env_vars}" ]] || (error "Helm vars do not exist for ${env_vars}" && exit 1)

args="--set image.tag=${version} "
[[ -f "$chart/values.yaml" ]] && args+="-f $chart/values.yaml "
[[ -f "$chart/secrets.yaml" ]] && args+="-f $chart/secrets.yaml "
[[ -f "$env_vars/values.yaml" ]] && args+="-f $env_vars/values.yaml "
[[ -f "$env_vars/secrets.yaml" ]] && args+="-f $env_vars/secrets.yaml "

eval $helm_cmd diff upgrade \
  --allow-unreleased \
  "$args" "$chart" "../helm/$chart"

#helm secrets update \
#   --install
