#!/usr/bin/env bash

set -euo pipefail

script_path="$(
  cd "$(dirname "$0")"
  pwd -P
)"
# shellcheck source=../.common
. "${script_path}/../.common"
# shellcheck source=.common
. "${script_path}/.common"

cd "${script_path}"/../../helm_vars

helm_cmd="helm secrets"

chart=${1?A Helm chart must be specified}
version=${2?A commit hash must be specified}
environment=${3?An environment must be specified}
namespace=${4?A Kubernetes namespace must be specified}

args=$(getHelmArgs "$chart" "$version" "$environment" "$namespace")

eval "$helm_cmd" diff upgrade \
  --allow-unreleased \
  "$args" "$chart" "../helm/$chart"
