#!/usr/bin/env bash

set -eo pipefail
SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
# shellcheck source=../.common
. "${SCRIPT_PATH}"/../.common

cd "${SCRIPT_PATH}/../../helm_vars"

helm_cmd="helm"

lint() {
  # First part of path may include global values/secrets
  IFS='/'
  read -ra paths <<< "$1"
  local chart="${paths[0]}"

  local files=""
  [[ -f "$chart/values.yaml" ]] && files+="-f $chart/values.yaml "
  [[ -f "$chart/secrets.yaml" ]] && files+="-f $chart/secrets.yaml "
  [[ -f "$1/values.yaml" ]] && files+="-f $1/values.yaml "
  [[ -f "$1/secrets.yaml" ]] && files+="-f $1/secrets.yaml "

  echo
  eval $helm_cmd lint "$files" "../helm/$chart"
  echo
}

if [[ -z "$1" ]]; then
  for chart in ./*/; do
    lint "${chart}"
  done
else
  [[ -d "$1" ]] || (echo "A helm_vars directory of $1 does not exist." && exit 1)
  lint "$1"
fi
