apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  TRENTON_WEB_LOGGING_LOG_TARGET: {{ .Values.config.TRENTON_WEB_LOGGING_LOG_TARGET }}
  TRENTON_WEB_FITBIT_CLIENT_ID: {{ .Values.config.TRENTON_WEB_FITBIT_CLIENT_ID }}
