apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
type: Opaque
data:
  TRENTON_WEB_FITBIT_CLIENT_SECRET: {{ .Values.config.TRENTON_WEB_FITBIT_CLIENT_SECRET | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}-google-service-account-key
  labels:
  {{- include "web.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.google.serviceAccountKey | b64enc | quote }}
