creation_rules:
  - path_regex: .config/(.*)\.enc\.env$
    gcp_kms: projects/trenton-production-c5cb9af5/locations/global/keyRings/sops-e5c13a4bbc73a75e/cryptoKeys/sops-key
  - path_regex: .kubernetes/overlays/{local,production}/secrets.*\.enc\.env$
    gcp_kms: projects/trenton-production-c5cb9af5/locations/global/keyRings/sops-e5c13a4bbc73a75e/cryptoKeys/sops-key
