version: "3.7"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    networks:
      - trenton
    env_file:
      - .env
    command: dotnet run --project src/Trenton.Webhooks/Trenton.Webhooks.fsproj
    volumes:
      - server_packages:/root/.nuget/packages
      - .:/usr/src/app
    ports:
      - 5000:5000
      - 5001:5001

volumes:
  server_packages: {}

networks:
  trenton:
    external: true
