##################################
FROM fsharp:10.7.0-netcore as dev

# Install Dockerize and requirements
RUN apt-get update && \
    apt-get --no-install-recommends install -y \
    musl
COPY --from=jwilder/dockerize:0.6.0 /usr/local/bin/dockerize /usr/local/bin

# Install Node.Js
RUN apt-get update --allow-releaseinfo-change && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    node -v

WORKDIR /usr/src/app/
ENTRYPOINT ["/usr/src/app/scripts/dev-entrypoint.sh"]


##################################
FROM fsharp:10.7.0-netcore as build

# Install Node.Js
RUN apt-get update --allow-releaseinfo-change && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    node -v

WORKDIR /usr/src/app/

COPY . .

RUN dotnet tool restore && dotnet paket restore
# RUN dotnet publish -c Release -o out src/Trenton.Web.Server/Trenton.Web.Server.fsproj


##################################
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as prod

COPY --from=build /usr/src/app/out .

ENTRYPOINT ["dotnet", "Trenton.Web.Server.dll"]

