##################################
FROM us-central1-docker.pkg.dev/trenton-production-c5cb9af5/trenton/fsharp-dev:33dda6b7be8f4313d0f0cfd4a6580fdef4f52069 as build

WORKDIR /usr/src/app/
ENTRYPOINT ["/usr/src/app/scripts/dev-entrypoint.sh"]


##################################
FROM us-central1-docker.pkg.dev/trenton-production-c5cb9af5/trenton/fsharp-dev:33dda6b7be8f4313d0f0cfd4a6580fdef4f52069 as build

WORKDIR /usr/src/app/

COPY . .

RUN dotnet tool restore && dotnet paket restore
RUN dotnet publish -c Release -o out src/Trenton.Web.Server/Trenton.Web.Server.fsproj


##################################
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as prod

COPY --from=build /usr/src/app/out .

ENTRYPOINT ["dotnet", "Trenton.Web.Server.dll"]

