apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhooks.fullname" . }}
  labels:
    {{- include "webhooks.labels" . | nindent 4 }}
data:
  TRENTON_WEBHOOKS_LOGGING_LOG_TARGET: {{ .Values.config.TRENTON_WEBHOOKS_LOGGING_LOG_TARGET }}
  TRENTON_WEBHOOKS_FITBIT_CLIENT_ID: {{ .Values.config.TRENTON_WEBHOOKS_FITBIT_CLIENT_ID }}
  TRENTON_WEBHOOKS_FITBIT_SUBSCRIBER_ID: {{ .Values.config.TRENTON_WEBHOOKS_FITBIT_SUBSCRIBER_ID }}
