apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhooks.fullname" . }}
  labels:
    {{- include "webhooks.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "webhooks.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "webhooks.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
#          envFrom:
#            - configMapRef:
#                name: webhooks-env-config
#            - secretRef:
#                name: webhooks-env-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 3
