apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhooks.fullname" . }}
  labels:
    {{- include "webhooks.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "webhooks.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
