#!/usr/bin/env bash

set -euo pipefail

script_path="$( cd "$(dirname "$0")" ; pwd -P )"
# shellcheck source=../.common
. ${script_path}/../.common

cd "${script_path}"/../../docker

for filename in $(find . -name Dockerfile*); do
  [[ -e "$filename" ]] || continue

  image_path=$(dirname "$filename")
  [[ -f "${image_path}/.imagename" ]] || (error "Missing .imagename file at ${image_path}" && exit 1)

  image_name=$(cat "${image_path}/.imagename")

  docker build \
    -t "${COMMON_DOCKER_IMAGE_BASE}/${image_name}:${COMMON_COMMIT_SHA}" \
    -f "${filename}" \
    "${image_path}"

  docker push "${COMMON_DOCKER_IMAGE_BASE}/${image_name}:${COMMON_COMMIT_SHA}"
done
