apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/managed-by: github-actions
  app.kubernetes.io/part-of: trenton-core
