#!/usr/bin/env bash

set -eo pipefail
SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
# shellcheck source=../.common
. "${SCRIPT_PATH}"/../.common
# shellcheck source=.common
. "${SCRIPT_PATH}"/.common

cd "${SCRIPT_PATH}/../../core"

docker build \
    -t "${COMMON_DOCKER_IMAGE_BASE}/${CORE_IMAGE_NAME}:${COMMON_COMMIT_SHA}" \
    -f Dockerfile \
    .
