#!/usr/bin/env bash

set -eo pipefail
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
# shellcheck source=../.common
. "${SCRIPT_PATH}"/../.common

cd "${SCRIPT_PATH}/../../core"

docker=1
while getopts "l" options; do
  case ${options} in
    l) docker=0 ;;
    *) error "Unknown option: -${OPTARG}"; exit 1 ;;
  esac
done

if [[ $docker == 1 ]]; then
  docker-compose \
    -f docker/docker-compose.webhooks.yaml \
    run --rm itests
else
  dotnet run --project test/Trenton.Webhooks.ITests/Trenton.Webhooks.ITests.fsproj
fi
