#!/usr/bin/env bash

set -eo pipefail
SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
# shellcheck source=../.common
. "${SCRIPT_PATH}"/../.common

cd "${SCRIPT_PATH}/../../core"

entrypoint=${1:-bash}
if [[ "$#" -gt 1 ]]; then
  shift
  cmd="$@"
fi

docker-compose run --rm \
  --service-ports \
  --entrypoint "${entrypoint}" \
  server \
  ${cmd}
