#!/usr/bin/env bash

set -eo pipefail
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
# shellcheck source=../.common
. "${SCRIPT_PATH}"/../.common

cd "${SCRIPT_PATH}/../../core"

docker=1
while getopts "l" options; do
  case ${options} in
    l)
      docker=0
      shift $((OPTIND-1))
      ;;
    *) error "Unknown option: -${OPTARG}"; exit 1 ;;
  esac
done

if [[ -z "$1" ]]; then
    cmd="scripts/test-all.sh"
else
    cmd="scripts/test.sh"
fi

docker-compose run --rm \
    server \
    "${cmd}" "$@"
