name: CLI
on:
  push:
    paths:
    - 'core/**'
    - '.github/workflows/cli.yaml'

jobs:
  utest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
    - uses: workflow/nix-shell-action@v1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: dotnet --version

