name: Core
on:
  push:
    paths:
    - 'core/**'
    - '.go/core/**'
    - '.github/workflows/core.yaml'

env:
  GCR_RW_TOKEN: ${{ secrets.GCR_RW_TOKEN }}
  GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud_auth.json
  GCLOUD_PROJECT: todo

jobs:
  utest:
    name: Run unit tests
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: GCloud login
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "${GCLOUD_AUTH}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
        gcloud auth activate-service-account --project=${GCLOUD_PROJECT} --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
    - name: Docker login
      run: echo $GCR_RW_TOKEN | docker login -u _json_key --password-stdin gcr.io
    - name: Install sops
      run: |
        sudo curl -fsSL https://github.com/mozilla/sops/releases/download/3.4.0/sops-3.4.0.linux -o /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops
    - name: Write .env file
      run: cd core && sops -d .config/ci.enc.env > .env
    - name: Run unit tests
      run: ./go core test

  itest:
    name: Run integration tests locally
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: GCloud login
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "${GCLOUD_AUTH}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
        gcloud auth activate-service-account --project=${GCLOUD_PROJECT} --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
    - name: Docker login
      run: echo $GCR_RW_TOKEN | docker login -u _json_key --password-stdin gcr.io
    - name: Install sops
      run: |
        sudo curl -fsSL https://github.com/mozilla/sops/releases/download/3.4.0/sops-3.4.0.linux -o /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops
    - name: Write .env file
      run: cd core && sops -d .config/ci.enc.env > .env
    - name: Start development server
      run: |
        ./go core start -d
        echo "Waiting for server to start to get some logs..."
        sleep 3m
        cd core
        docker-compose logs server
    - name: Run integration tests
      env:
        TEST_SERVER_BASE: http://server
        TEST_SEVER_PORT: 5000
      run: ./go core itest

  publish:
    name: Publish Docker image
    needs: [utest, itest]
    if: endsWith(github.ref, 'master')
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Docker login
      run: echo $GCR_RW_TOKEN | docker login -u _json_key --password-stdin gcr.io
    - name: Publish Docker image
      run: ./go core publish

  deploy:
    name: Deploy
    needs: [publish]
    if: endsWith(github.ref, 'master')
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: GCloud login
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "${GCLOUD_AUTH}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
        gcloud auth activate-service-account --project=${GCLOUD_PROJECT} --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
    - name: Install sops
      run: |
        sudo curl -fsSL https://github.com/mozilla/sops/releases/download/3.4.0/sops-3.4.0.linux -o /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops
    - name: Install kustomize
      run: |
        cd /usr/local/bin
        sudo curl -sL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
    - name: Configure kubectl
      run: gcloud beta container clusters get-credentials apps --region us-central1
    - name: Deploy
      run: |
        ./go core deploy production ${GITHUB_SHA}
