name: Core
on:
  push:
    paths:
    - core/**
    - .go/core/**
    - .github/workflows/core.yaml

#env:
  GCR_RW_TOKEN: ${{ secrets.GCR_RW_TOKEN }}
  GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcloud_auth.json
  GCLOUD_PROJECT_DEVELOPMENT: development

jobs:
  publish:
    name: Publish Docker image
    if: endsWith(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Docker login
      run: echo $GCR_RW_TOKEN | docker login -u _json_key --password-stdin gcr.io
    - name: Publish Docker image
      run: ./go core publish

  deploy-development:
    name: Deploy to Development
    needs: [publish]
    if: endsWith(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: GCloud login
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH_DEVELOPMENT }}
      run: |
        echo "${GCLOUD_AUTH}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
        gcloud auth activate-service-account --project=${GCLOUD_PROJECT_DEVELOPMENT} --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
    - name: Install sops
      run: |
        sudo curl -fsSL https://github.com/mozilla/sops/releases/download/3.4.0/sops-3.4.0.linux -o /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops
    - name: Install kustomize
      run: |
        cd /usr/local/bin
        sudo curl -sL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
    - name: Configure kubectl
      run: gcloud beta container clusters get-credentials apps --region us-central1
    - name: Deploy
      run: |
        ./go core deploy development ${GITHUB_SHA}
