name: Docker Images
on:
  push:
    paths:
      - docker/**
      - .go/docker/**
      - .github/workflows/docker.yaml

env:
  GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
  GCLOUD_PROJECT: trenton-production-c5cb9af5

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Docker login
        run: echo $GCLOUD_AUTH | docker login -u _json_key --password-stdin us-central1-docker.pkg.dev
      - name: Build and push
        run: ./go docker build
